Dir[File.dirname(__FILE__) + '/test/*.rb'].each {|file| require file }

test = PageTest.new
test.creating_a_new_page_using_the_factory
test.page_has_no_content_to_start_with
test.page_with_no_content_is_considered_a_new_page
test.page_can_be_given_content

test = PageFilePersistorTest.new
test.figuring_out_filename_with_just_one_word
test.figuring_out_filename_with_more_than_one_word
test.figuring_out_filename_with_more_than_one_space

test = PageFactoryTest.new
test.saving_a_page_and_retrieving_it_again
test.saving_multiple_pages
test.page_is_created_in_the_file_system
test.page_content_is_written_to_the_file
test.page_content_is_read_from_the_file
test.tear_down

test = WebserverTest.new
test.finding_a_static_page
test.parsing_page_title
test.parsing_a_complex_page_title
test.displaying_title_on_the_page
test.displaying_content_for_existing_page
test.showing_a_page_that_does_not_exist_yet
test.showing_a_form_to_create_a_page
test.tear_down
